/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sopadeletras;

/**
 *
 * @author ayahzaheraldeen
 */
public class InstructionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form InstructionsFrame
     */
    public InstructionsFrame() {
        initComponents();
        this.jTextArea1.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();

        jLabel1.setText("Por favor lea las siguientes instrucciones antes de comenzar el juego.");

        jLabel2.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 37, 109));
        jLabel2.setText("Instrucciones: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 235, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(244, 235, 254));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1.Comience cargando el diccionario desde el cual se leerán \nlas letras y palabras de la sopa de letras, usando el botón \n\"Caragar Archivo\"\nASEGÚRESE DE QUE CONTIENE SOLO 16 LETRAS SEPARADAS!\n\n2.Para encontrar todas las palabras en el diccionario dado, \nhaga clic en el botón \"Buscar Palabras\" y elija el método \nde búsqueda (BFS o DFS) usando el cuadro desplegable.\nLas palabras encontradas se colorearán en verde.\n\n3.Para encontrar una palabra en particular, puede escribir \nla palabra en el espacio dado y buscarla o guardarla en el \ndiccionario. Elija el método de búsqueda (BFS o DFS) \nusando el cuadro desplegable.\nDeberías poder visualizar el árbol transversal de \nla palabra una vez encontrada.\n\n4.¡Por último, guarda el diccionario nuevamente en un \narchivo que elijas usando el botón \"Guardar\"!");
        jTextArea1.setCaretColor(new java.awt.Color(255, 102, 51));
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 204, 255));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 160));

        jLabel3.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 37, 109));
        jLabel3.setText("Instrucciones:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 0, 108));
        jLabel4.setText("¡Buena suerte y diviertete!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, -1));

        jLabel5.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 0, 108));
        jLabel5.setText("Lea atentamente las instrucciones antes de comenzar el juego.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 20));

        CloseButton.setBackground(new java.awt.Color(111, 84, 174));
        CloseButton.setFont(new java.awt.Font("BM Hanna 11yrs Old", 1, 14)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 255, 255));
        CloseButton.setText("Cerrar");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == CloseButton); {
      this.dispose();
        }
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
